/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.retrodim.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.mcreator.retrodim.block.*;
import net.mcreator.retrodim.RetrodimMod;

public class RetrodimModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(RetrodimMod.MODID);
	public static final DeferredBlock<Block> RETRODIMENSION_PORTAL;
	public static final DeferredBlock<Block> RETRO_PURPLE_BLOCK;
	public static final DeferredBlock<Block> RETRO_ORANGE_BLOCK;
	public static final DeferredBlock<Block> RETRO_BLUE_BLOCK;
	public static final DeferredBlock<Block> NEON_BLOCK_RED;
	public static final DeferredBlock<Block> NEON_BLOCK_ORANGE;
	public static final DeferredBlock<Block> NEON_BLOCK_BLACK;
	public static final DeferredBlock<Block> NEON_BLOCK_YELLOW;
	public static final DeferredBlock<Block> NEON_BLOCK_LIME;
	public static final DeferredBlock<Block> NEON_BLOCK_LIGHT_BLUE;
	public static final DeferredBlock<Block> NEON_BLOCK_MAGENTA;
	public static final DeferredBlock<Block> NEON_BLOCK_WHITE;
	public static final DeferredBlock<Block> NEON_BLOCK_BLUE;
	public static final DeferredBlock<Block> NEON_BLOCK_GREEN;
	public static final DeferredBlock<Block> NEON_BLOCK_LIGHT_YELLOW;
	public static final DeferredBlock<Block> NEON_BLOCK_BROWN;
	public static final DeferredBlock<Block> NEON_BLOCK_PURPLE;
	public static final DeferredBlock<Block> NEON_BLOCK_PINK;
	public static final DeferredBlock<Block> NEON_BLOCK_CYAN;
	public static final DeferredBlock<Block> NEON_BLOCK_GRAY;
	public static final DeferredBlock<Block> NEON_BLOCK_LIGHT_GRAY;
	public static final DeferredBlock<Block> NEON_BLOCK_BUBBLEGUM;
	public static final DeferredBlock<Block> FLASHING_RED_2S_A;
	public static final DeferredBlock<Block> FLASHING_RED_2S_B;
	public static final DeferredBlock<Block> FLICKERING_RED_5S_A;
	public static final DeferredBlock<Block> FLASHING_MAGENTA_2S_A;
	public static final DeferredBlock<Block> FLASHING_MAGENTA_2S_B;
	public static final DeferredBlock<Block> FLASHING_RED_1S_X;
	public static final DeferredBlock<Block> FLASHING_RED_1S_Y;
	public static final DeferredBlock<Block> FLASHING_RED_1S_Z;
	public static final DeferredBlock<Block> FLICKERING_RED_3S_A;
	public static final DeferredBlock<Block> FLICKERING_RED_3S_B;
	public static final DeferredBlock<Block> FLICKERING_RED_3S_C;
	public static final DeferredBlock<Block> PULSING_RED_2S_A;
	public static final DeferredBlock<Block> FLASHING_MAGENTA_1S_X;
	public static final DeferredBlock<Block> FLASHING_MAGENTA_1S_Y;
	public static final DeferredBlock<Block> FLASHING_MAGENTA_1S_Z;
	public static final DeferredBlock<Block> FLICKERING_MAGENTA_3S_A;
	public static final DeferredBlock<Block> FLICKERING_MAGENTA_3S_B;
	public static final DeferredBlock<Block> FLICKERING_MAGENTA_3S_C;
	public static final DeferredBlock<Block> FLICKERING_MAGENTA_5S_A;
	public static final DeferredBlock<Block> PULSING_MAGENTA_2S_A;
	public static final DeferredBlock<Block> FLASHING_BLUE_1S_X;
	public static final DeferredBlock<Block> FLASHING_BLUE_1S_Y;
	public static final DeferredBlock<Block> FLASHING_BLUE_1S_Z;
	public static final DeferredBlock<Block> FLASHING_BLUE_2S_A;
	public static final DeferredBlock<Block> FLASHING_BLUE_2S_B;
	public static final DeferredBlock<Block> FLICKERING_BLUE_3S_A;
	public static final DeferredBlock<Block> FLICKERING_BLUE_3S_B;
	public static final DeferredBlock<Block> FLICKERING_BLUE_3S_C;
	public static final DeferredBlock<Block> FLICKERING_BLUE_5S_A;
	public static final DeferredBlock<Block> PULSING_BLUE_2S_A;
	public static final DeferredBlock<Block> FLASHING_BROWN_1S_X;
	public static final DeferredBlock<Block> FLASHING_BROWN_1S_Y;
	public static final DeferredBlock<Block> FLASHING_BROWN_1S_Z;
	public static final DeferredBlock<Block> FLASHING_BROWN_2S_A;
	public static final DeferredBlock<Block> FLASHING_BROWN_2S_B;
	public static final DeferredBlock<Block> FLICKERING_BROWN_3S_A;
	public static final DeferredBlock<Block> FLICKERING_BROWN_3S_B;
	public static final DeferredBlock<Block> FLICKERING_BROWN_3S_C;
	public static final DeferredBlock<Block> FLICKERING_BROWN_5S_A;
	public static final DeferredBlock<Block> PULSING_BROWN_2S_A;
	public static final DeferredBlock<Block> FLASHING_BUBBLEGUM_1S_X;
	public static final DeferredBlock<Block> FLASHING_BUBBLEGUM_1S_Y;
	public static final DeferredBlock<Block> FLASHING_BUBBLEGUM_1S_Z;
	public static final DeferredBlock<Block> FLASHING_BUBBLEGUM_2S_A;
	public static final DeferredBlock<Block> FLASHING_BUBBLEGUM_2S_B;
	public static final DeferredBlock<Block> FLICKERING_BUBBLEGUM_3S_A;
	public static final DeferredBlock<Block> FLICKERING_BUBBLEGUM_3S_B;
	public static final DeferredBlock<Block> FLICKERING_BUBBLEGUM_3S_C;
	public static final DeferredBlock<Block> FLICKERING_BUBBLEGUM_5S_A;
	public static final DeferredBlock<Block> PULSING_BUBBLEGUM_2S_A;
	public static final DeferredBlock<Block> FLASHING_CYAN_1S_X;
	public static final DeferredBlock<Block> FLASHING_CYAN_1S_Y;
	public static final DeferredBlock<Block> FLASHING_CYAN_1S_Z;
	public static final DeferredBlock<Block> FLASHING_CYAN_2S_A;
	public static final DeferredBlock<Block> FLASHING_CYAN_2S_B;
	public static final DeferredBlock<Block> FLICKERING_CYAN_3S_A;
	public static final DeferredBlock<Block> FLICKERING_CYAN_3S_B;
	public static final DeferredBlock<Block> FLICKERING_CYAN_3S_C;
	public static final DeferredBlock<Block> FLICKERING_CYAN_5S_A;
	public static final DeferredBlock<Block> PULSING_CYAN_2S_A;
	public static final DeferredBlock<Block> FLASHING_GRAY_1S_X;
	public static final DeferredBlock<Block> FLASHING_GRAY_1S_Y;
	public static final DeferredBlock<Block> FLASHING_GRAY_1S_Z;
	public static final DeferredBlock<Block> FLASHING_GRAY_2S_A;
	public static final DeferredBlock<Block> FLASHING_GRAY_2S_B;
	public static final DeferredBlock<Block> FLICKERING_GRAY_3S_A;
	public static final DeferredBlock<Block> FLICKERING_GRAY_3S_B;
	public static final DeferredBlock<Block> FLICKERING_GRAY_3S_C;
	public static final DeferredBlock<Block> FLICKERING_GRAY_5S_A;
	public static final DeferredBlock<Block> PULSING_GRAY_2S_A;
	public static final DeferredBlock<Block> FLASHING_GREEN_1S_X;
	public static final DeferredBlock<Block> FLASHING_GREEN_1S_Y;
	public static final DeferredBlock<Block> FLASHING_GREEN_1S_Z;
	public static final DeferredBlock<Block> FLASHING_GREEN_2S_A;
	public static final DeferredBlock<Block> FLASHING_GREEN_2S_B;
	public static final DeferredBlock<Block> FLICKERING_GREEN_3S_A;
	public static final DeferredBlock<Block> FLICKERING_GREEN_3S_B;
	public static final DeferredBlock<Block> FLICKERING_GREEN_3S_C;
	public static final DeferredBlock<Block> FLICKERING_GREEN_5S_A;
	public static final DeferredBlock<Block> PULSING_GREEN_2S_A;
	public static final DeferredBlock<Block> FLASHING_LIGHT_BLUE_1S_X;
	public static final DeferredBlock<Block> FLASHING_LIGHT_BLUE_1S_Y;
	public static final DeferredBlock<Block> FLASHING_LIGHT_BLUE_1S_Z;
	public static final DeferredBlock<Block> FLASHING_LIGHT_BLUE_2S_A;
	public static final DeferredBlock<Block> FLASHING_LIGHT_BLUE_2S_B;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_BLUE_3S_A;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_BLUE_3S_B;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_BLUE_3S_C;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_BLUE_5S_A;
	public static final DeferredBlock<Block> PULSING_LIGHT_BLUE_2S_A;
	public static final DeferredBlock<Block> FLASHING_LIGHT_GRAY_1S_X;
	public static final DeferredBlock<Block> FLASHING_LIGHT_GRAY_1S_Y;
	public static final DeferredBlock<Block> FLASHING_LIGHT_GRAY_1S_Z;
	public static final DeferredBlock<Block> FLASHING_LIGHT_GRAY_2S_A;
	public static final DeferredBlock<Block> FLASHING_LIGHT_GRAY_2S_B;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_GRAY_3S_A;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_GRAY_3S_B;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_GRAY_3S_C;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_GRAY_5S_A;
	public static final DeferredBlock<Block> PULSING_LIGHT_GRAY_2S_A;
	public static final DeferredBlock<Block> FLASHING_LIGHT_YELLOW_1S_X;
	public static final DeferredBlock<Block> FLASHING_LIGHT_YELLOW_1S_Y;
	public static final DeferredBlock<Block> FLASHING_LIGHT_YELLOW_1S_Z;
	public static final DeferredBlock<Block> FLASHING_LIGHT_YELLOW_2S_A;
	public static final DeferredBlock<Block> FLASHING_LIGHT_YELLOW_2S_B;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_YELLOW_3S_A;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_YELLOW_3S_B;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_YELLOW_3S_C;
	public static final DeferredBlock<Block> FLICKERING_LIGHT_YELLOW_5S_A;
	public static final DeferredBlock<Block> PULSING_LIGHT_YELLOW_2S_A;
	public static final DeferredBlock<Block> FLASHING_LIME_1S_X;
	public static final DeferredBlock<Block> FLASHING_LIME_1S_Y;
	public static final DeferredBlock<Block> FLASHING_LIME_1S_Z;
	public static final DeferredBlock<Block> FLASHING_LIME_2S_A;
	public static final DeferredBlock<Block> FLASHING_LIME_2S_B;
	public static final DeferredBlock<Block> FLICKERING_LIME_3S_A;
	public static final DeferredBlock<Block> FLICKERING_LIME_3S_B;
	public static final DeferredBlock<Block> FLICKERING_LIME_3S_C;
	public static final DeferredBlock<Block> FLICKERING_LIME_5S_A;
	public static final DeferredBlock<Block> PULSING_LIME_2S_A;
	public static final DeferredBlock<Block> FLASHING_ORANGE_1S_X;
	public static final DeferredBlock<Block> FLASHING_ORANGE_1S_Y;
	public static final DeferredBlock<Block> FLASHING_ORANGE_1S_Z;
	public static final DeferredBlock<Block> FLASHING_ORANGE_2S_A;
	public static final DeferredBlock<Block> FLASHING_ORANGE_2S_B;
	public static final DeferredBlock<Block> FLICKERING_ORANGE_3S_A;
	public static final DeferredBlock<Block> FLICKERING_ORANGE_3S_B;
	public static final DeferredBlock<Block> FLICKERING_ORANGE_3S_C;
	public static final DeferredBlock<Block> FLICKERING_ORANGE_5S_A;
	public static final DeferredBlock<Block> PULSING_ORANGE_2S_A;
	public static final DeferredBlock<Block> FLASHING_PINK_1S_X;
	public static final DeferredBlock<Block> FLASHING_PINK_1S_Y;
	public static final DeferredBlock<Block> FLASHING_PINK_1S_Z;
	public static final DeferredBlock<Block> FLASHING_PINK_2S_A;
	public static final DeferredBlock<Block> FLASHING_PINK_2S_B;
	public static final DeferredBlock<Block> FLICKERING_PINK_3S_A;
	public static final DeferredBlock<Block> FLICKERING_PINK_3S_B;
	public static final DeferredBlock<Block> FLICKERING_PINK_3S_C;
	public static final DeferredBlock<Block> FLICKERING_PINK_5S_A;
	public static final DeferredBlock<Block> PULSING_PINK_2S_A;
	public static final DeferredBlock<Block> FLASHING_PURPLE_1S_X;
	public static final DeferredBlock<Block> FLASHING_PURPLE_1S_Y;
	public static final DeferredBlock<Block> FLASHING_PURPLE_1S_Z;
	public static final DeferredBlock<Block> FLASHING_PURPLE_2S_A;
	public static final DeferredBlock<Block> FLASHING_PURPLE_2S_B;
	public static final DeferredBlock<Block> FLICKERING_PURPLE_3S_A;
	public static final DeferredBlock<Block> FLICKERING_PURPLE_3S_B;
	public static final DeferredBlock<Block> FLICKERING_PURPLE_3S_C;
	public static final DeferredBlock<Block> FLICKERING_PURPLE_5S_A;
	public static final DeferredBlock<Block> PULSING_PURPLE_2S_A;
	public static final DeferredBlock<Block> FLASHING_WHITE_1S_X;
	public static final DeferredBlock<Block> FLASHING_WHITE_1S_Y;
	public static final DeferredBlock<Block> FLASHING_WHITE_1S_Z;
	public static final DeferredBlock<Block> FLASHING_WHITE_2S_A;
	public static final DeferredBlock<Block> FLASHING_WHITE_2S_B;
	public static final DeferredBlock<Block> FLICKERING_WHITE_3S_A;
	public static final DeferredBlock<Block> FLICKERING_WHITE_3S_B;
	public static final DeferredBlock<Block> FLICKERING_WHITE_3S_C;
	public static final DeferredBlock<Block> FLICKERING_WHITE_5S_A;
	public static final DeferredBlock<Block> PULSING_WHITE_2S_A;
	public static final DeferredBlock<Block> FLASHING_YELLOW_1S_X;
	public static final DeferredBlock<Block> FLASHING_YELLOW_1S_Y;
	public static final DeferredBlock<Block> FLASHING_YELLOW_1S_Z;
	public static final DeferredBlock<Block> FLASHING_YELLOW_2S_A;
	public static final DeferredBlock<Block> FLASHING_YELLOW_2S_B;
	public static final DeferredBlock<Block> FLICKERING_YELLOW_3S_A;
	public static final DeferredBlock<Block> FLICKERING_YELLOW_3S_B;
	public static final DeferredBlock<Block> FLICKERING_YELLOW_3S_C;
	public static final DeferredBlock<Block> FLICKERING_YELLOW_5S_A;
	public static final DeferredBlock<Block> PULSING_YELLOW_2S_A;
	public static final DeferredBlock<Block> ARCADE_CABINET;
	public static final DeferredBlock<Block> OPEN_SIGN_RED;
	public static final DeferredBlock<Block> OPEN_SIGN_PINK;
	public static final DeferredBlock<Block> NEON_CYBER_SIGN;
	public static final DeferredBlock<Block> NEON_EDGE_CYAN_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_MAGENTA_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_MAGENTA_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_CYAN_BLOCK;
	public static final DeferredBlock<Block> BIT_WISP;
	public static final DeferredBlock<Block> RETRO_GREEN_BLOCK;
	public static final DeferredBlock<Block> RETRO_RED_BLOCK;
	public static final DeferredBlock<Block> RETRO_YELLOW_BLOCK;
	public static final DeferredBlock<Block> RETRO_WHITE_BLOCK;
	public static final DeferredBlock<Block> RETRO_PASTEL_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_BLUE_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_BROWN_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_BUBBLEGUM_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_GRAY_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_GREEN_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_LIGHT_BLUE_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_LIGHT_GRAY_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_LIGHT_YELLOW_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_LIME_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_ORANGE_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_PINK_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_PURPLE_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_RED_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_WHITE_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_YELLOW_BLOCK;
	public static final DeferredBlock<Block> NEON_EDGE_BLACK_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_BLUE_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_BROWN_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_BUBBLEGUM_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_GRAY_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_GREEN_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_LIGHT_BLUE_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_LIGHT_GRAY_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_LIGHT_YELLOW_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_LIME_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_ORANGE_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_PINK_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_PURPLE_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_RED_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_WHITE_BLOCK;
	public static final DeferredBlock<Block> NEON_DARK_YELLOW_BLOCK;
	static {
		RETRODIMENSION_PORTAL = REGISTRY.register("retrodimension_portal", RetrodimensionPortalBlock::new);
		RETRO_PURPLE_BLOCK = REGISTRY.register("retro_purple_block", RetroPurpleBlockBlock::new);
		RETRO_ORANGE_BLOCK = REGISTRY.register("retro_orange_block", RetroOrangeBlockBlock::new);
		RETRO_BLUE_BLOCK = REGISTRY.register("retro_blue_block", RetroBlueBlockBlock::new);
		NEON_BLOCK_RED = REGISTRY.register("neon_block_red", NeonBlockRedBlock::new);
		NEON_BLOCK_ORANGE = REGISTRY.register("neon_block_orange", NeonBlockOrangeBlock::new);
		NEON_BLOCK_BLACK = REGISTRY.register("neon_block_black", NeonBlockBlackBlock::new);
		NEON_BLOCK_YELLOW = REGISTRY.register("neon_block_yellow", NeonBlockYellowBlock::new);
		NEON_BLOCK_LIME = REGISTRY.register("neon_block_lime", NeonBlockLimeBlock::new);
		NEON_BLOCK_LIGHT_BLUE = REGISTRY.register("neon_block_light_blue", NeonBlockLightBlueBlock::new);
		NEON_BLOCK_MAGENTA = REGISTRY.register("neon_block_magenta", NeonBlockMagentaBlock::new);
		NEON_BLOCK_WHITE = REGISTRY.register("neon_block_white", NeonBlockWhiteBlock::new);
		NEON_BLOCK_BLUE = REGISTRY.register("neon_block_blue", NeonBlockBlueBlock::new);
		NEON_BLOCK_GREEN = REGISTRY.register("neon_block_green", NeonBlockGreenBlock::new);
		NEON_BLOCK_LIGHT_YELLOW = REGISTRY.register("neon_block_light_yellow", NeonBlockLightYellowBlock::new);
		NEON_BLOCK_BROWN = REGISTRY.register("neon_block_brown", NeonBlockBrownBlock::new);
		NEON_BLOCK_PURPLE = REGISTRY.register("neon_block_purple", NeonBlockPurpleBlock::new);
		NEON_BLOCK_PINK = REGISTRY.register("neon_block_pink", NeonBlockPinkBlock::new);
		NEON_BLOCK_CYAN = REGISTRY.register("neon_block_cyan", NeonBlockCyanBlock::new);
		NEON_BLOCK_GRAY = REGISTRY.register("neon_block_gray", NeonBlockGrayBlock::new);
		NEON_BLOCK_LIGHT_GRAY = REGISTRY.register("neon_block_light_gray", NeonBlockLightGrayBlock::new);
		NEON_BLOCK_BUBBLEGUM = REGISTRY.register("neon_block_bubblegum", NeonBlockBubblegumBlock::new);
		FLASHING_RED_2S_A = REGISTRY.register("flashing_red_2s_a", FlashingRed2sABlock::new);
		FLASHING_RED_2S_B = REGISTRY.register("flashing_red_2s_b", FlashingRed2sBBlock::new);
		FLICKERING_RED_5S_A = REGISTRY.register("flickering_red_5s_a", FlickeringRed5sABlock::new);
		FLASHING_MAGENTA_2S_A = REGISTRY.register("flashing_magenta_2s_a", FlashingMagenta2sABlock::new);
		FLASHING_MAGENTA_2S_B = REGISTRY.register("flashing_magenta_2s_b", FlashingMagenta2sBBlock::new);
		FLASHING_RED_1S_X = REGISTRY.register("flashing_red_1s_x", FlashingRed1sXBlock::new);
		FLASHING_RED_1S_Y = REGISTRY.register("flashing_red_1s_y", FlashingRed1sYBlock::new);
		FLASHING_RED_1S_Z = REGISTRY.register("flashing_red_1s_z", FlashingRed1sZBlock::new);
		FLICKERING_RED_3S_A = REGISTRY.register("flickering_red_3s_a", FlickeringRed3sABlock::new);
		FLICKERING_RED_3S_B = REGISTRY.register("flickering_red_3s_b", FlickeringRed3sBBlock::new);
		FLICKERING_RED_3S_C = REGISTRY.register("flickering_red_3s_c", FlickeringRed3sCBlock::new);
		PULSING_RED_2S_A = REGISTRY.register("pulsing_red_2s_a", PulsingRed2sABlock::new);
		FLASHING_MAGENTA_1S_X = REGISTRY.register("flashing_magenta_1s_x", FlashingMagenta1sXBlock::new);
		FLASHING_MAGENTA_1S_Y = REGISTRY.register("flashing_magenta_1s_y", FlashingMagenta1sYBlock::new);
		FLASHING_MAGENTA_1S_Z = REGISTRY.register("flashing_magenta_1s_z", FlashingMagenta1sZBlock::new);
		FLICKERING_MAGENTA_3S_A = REGISTRY.register("flickering_magenta_3s_a", FlickeringMagenta3sABlock::new);
		FLICKERING_MAGENTA_3S_B = REGISTRY.register("flickering_magenta_3s_b", FlickeringMagenta3sBBlock::new);
		FLICKERING_MAGENTA_3S_C = REGISTRY.register("flickering_magenta_3s_c", FlickeringMagenta3sCBlock::new);
		FLICKERING_MAGENTA_5S_A = REGISTRY.register("flickering_magenta_5s_a", FlickeringMagenta5sABlock::new);
		PULSING_MAGENTA_2S_A = REGISTRY.register("pulsing_magenta_2s_a", PulsingMagenta2sABlock::new);
		FLASHING_BLUE_1S_X = REGISTRY.register("flashing_blue_1s_x", FlashingBlue1sXBlock::new);
		FLASHING_BLUE_1S_Y = REGISTRY.register("flashing_blue_1s_y", FlashingBlue1sYBlock::new);
		FLASHING_BLUE_1S_Z = REGISTRY.register("flashing_blue_1s_z", FlashingBlue1sZBlock::new);
		FLASHING_BLUE_2S_A = REGISTRY.register("flashing_blue_2s_a", FlashingBlue2sABlock::new);
		FLASHING_BLUE_2S_B = REGISTRY.register("flashing_blue_2s_b", FlashingBlue2sBBlock::new);
		FLICKERING_BLUE_3S_A = REGISTRY.register("flickering_blue_3s_a", FlickeringBlue3sABlock::new);
		FLICKERING_BLUE_3S_B = REGISTRY.register("flickering_blue_3s_b", FlickeringBlue3sBBlock::new);
		FLICKERING_BLUE_3S_C = REGISTRY.register("flickering_blue_3s_c", FlickeringBlue3sCBlock::new);
		FLICKERING_BLUE_5S_A = REGISTRY.register("flickering_blue_5s_a", FlickeringBlue5sABlock::new);
		PULSING_BLUE_2S_A = REGISTRY.register("pulsing_blue_2s_a", PulsingBlue2sABlock::new);
		FLASHING_BROWN_1S_X = REGISTRY.register("flashing_brown_1s_x", FlashingBrown1sXBlock::new);
		FLASHING_BROWN_1S_Y = REGISTRY.register("flashing_brown_1s_y", FlashingBrown1sYBlock::new);
		FLASHING_BROWN_1S_Z = REGISTRY.register("flashing_brown_1s_z", FlashingBrown1sZBlock::new);
		FLASHING_BROWN_2S_A = REGISTRY.register("flashing_brown_2s_a", FlashingBrown2sABlock::new);
		FLASHING_BROWN_2S_B = REGISTRY.register("flashing_brown_2s_b", FlashingBrown2sBBlock::new);
		FLICKERING_BROWN_3S_A = REGISTRY.register("flickering_brown_3s_a", FlickeringBrown3sABlock::new);
		FLICKERING_BROWN_3S_B = REGISTRY.register("flickering_brown_3s_b", FlickeringBrown3sBBlock::new);
		FLICKERING_BROWN_3S_C = REGISTRY.register("flickering_brown_3s_c", FlickeringBrown3sCBlock::new);
		FLICKERING_BROWN_5S_A = REGISTRY.register("flickering_brown_5s_a", FlickeringBrown5sABlock::new);
		PULSING_BROWN_2S_A = REGISTRY.register("pulsing_brown_2s_a", PulsingBrown2sABlock::new);
		FLASHING_BUBBLEGUM_1S_X = REGISTRY.register("flashing_bubblegum_1s_x", FlashingBubblegum1sXBlock::new);
		FLASHING_BUBBLEGUM_1S_Y = REGISTRY.register("flashing_bubblegum_1s_y", FlashingBubblegum1sYBlock::new);
		FLASHING_BUBBLEGUM_1S_Z = REGISTRY.register("flashing_bubblegum_1s_z", FlashingBubblegum1sZBlock::new);
		FLASHING_BUBBLEGUM_2S_A = REGISTRY.register("flashing_bubblegum_2s_a", FlashingBubblegum2sABlock::new);
		FLASHING_BUBBLEGUM_2S_B = REGISTRY.register("flashing_bubblegum_2s_b", FlashingBubblegum2sBBlock::new);
		FLICKERING_BUBBLEGUM_3S_A = REGISTRY.register("flickering_bubblegum_3s_a", FlickeringBubblegum3sABlock::new);
		FLICKERING_BUBBLEGUM_3S_B = REGISTRY.register("flickering_bubblegum_3s_b", FlickeringBubblegum3sBBlock::new);
		FLICKERING_BUBBLEGUM_3S_C = REGISTRY.register("flickering_bubblegum_3s_c", FlickeringBubblegum3sCBlock::new);
		FLICKERING_BUBBLEGUM_5S_A = REGISTRY.register("flickering_bubblegum_5s_a", FlickeringBubblegum5sABlock::new);
		PULSING_BUBBLEGUM_2S_A = REGISTRY.register("pulsing_bubblegum_2s_a", PulsingBubblegum2sABlock::new);
		FLASHING_CYAN_1S_X = REGISTRY.register("flashing_cyan_1s_x", FlashingCyan1sXBlock::new);
		FLASHING_CYAN_1S_Y = REGISTRY.register("flashing_cyan_1s_y", FlashingCyan1sYBlock::new);
		FLASHING_CYAN_1S_Z = REGISTRY.register("flashing_cyan_1s_z", FlashingCyan1sZBlock::new);
		FLASHING_CYAN_2S_A = REGISTRY.register("flashing_cyan_2s_a", FlashingCyan2sABlock::new);
		FLASHING_CYAN_2S_B = REGISTRY.register("flashing_cyan_2s_b", FlashingCyan2sBBlock::new);
		FLICKERING_CYAN_3S_A = REGISTRY.register("flickering_cyan_3s_a", FlickeringCyan3sABlock::new);
		FLICKERING_CYAN_3S_B = REGISTRY.register("flickering_cyan_3s_b", FlickeringCyan3sBBlock::new);
		FLICKERING_CYAN_3S_C = REGISTRY.register("flickering_cyan_3s_c", FlickeringCyan3sCBlock::new);
		FLICKERING_CYAN_5S_A = REGISTRY.register("flickering_cyan_5s_a", FlickeringCyan5sABlock::new);
		PULSING_CYAN_2S_A = REGISTRY.register("pulsing_cyan_2s_a", PulsingCyan2sABlock::new);
		FLASHING_GRAY_1S_X = REGISTRY.register("flashing_gray_1s_x", FlashingGray1sXBlock::new);
		FLASHING_GRAY_1S_Y = REGISTRY.register("flashing_gray_1s_y", FlashingGray1sYBlock::new);
		FLASHING_GRAY_1S_Z = REGISTRY.register("flashing_gray_1s_z", FlashingGray1sZBlock::new);
		FLASHING_GRAY_2S_A = REGISTRY.register("flashing_gray_2s_a", FlashingGray2sABlock::new);
		FLASHING_GRAY_2S_B = REGISTRY.register("flashing_gray_2s_b", FlashingGray2sBBlock::new);
		FLICKERING_GRAY_3S_A = REGISTRY.register("flickering_gray_3s_a", FlickeringGray3sABlock::new);
		FLICKERING_GRAY_3S_B = REGISTRY.register("flickering_gray_3s_b", FlickeringGray3sBBlock::new);
		FLICKERING_GRAY_3S_C = REGISTRY.register("flickering_gray_3s_c", FlickeringGray3sCBlock::new);
		FLICKERING_GRAY_5S_A = REGISTRY.register("flickering_gray_5s_a", FlickeringGray5sABlock::new);
		PULSING_GRAY_2S_A = REGISTRY.register("pulsing_gray_2s_a", PulsingGray2sABlock::new);
		FLASHING_GREEN_1S_X = REGISTRY.register("flashing_green_1s_x", FlashingGreen1sXBlock::new);
		FLASHING_GREEN_1S_Y = REGISTRY.register("flashing_green_1s_y", FlashingGreen1sYBlock::new);
		FLASHING_GREEN_1S_Z = REGISTRY.register("flashing_green_1s_z", FlashingGreen1sZBlock::new);
		FLASHING_GREEN_2S_A = REGISTRY.register("flashing_green_2s_a", FlashingGreen2sABlock::new);
		FLASHING_GREEN_2S_B = REGISTRY.register("flashing_green_2s_b", FlashingGreen2sBBlock::new);
		FLICKERING_GREEN_3S_A = REGISTRY.register("flickering_green_3s_a", FlickeringGreen3sABlock::new);
		FLICKERING_GREEN_3S_B = REGISTRY.register("flickering_green_3s_b", FlickeringGreen3sBBlock::new);
		FLICKERING_GREEN_3S_C = REGISTRY.register("flickering_green_3s_c", FlickeringGreen3sCBlock::new);
		FLICKERING_GREEN_5S_A = REGISTRY.register("flickering_green_5s_a", FlickeringGreen5sABlock::new);
		PULSING_GREEN_2S_A = REGISTRY.register("pulsing_green_2s_a", PulsingGreen2sABlock::new);
		FLASHING_LIGHT_BLUE_1S_X = REGISTRY.register("flashing_light_blue_1s_x", FlashingLightBlue1sXBlock::new);
		FLASHING_LIGHT_BLUE_1S_Y = REGISTRY.register("flashing_light_blue_1s_y", FlashingLightBlue1sYBlock::new);
		FLASHING_LIGHT_BLUE_1S_Z = REGISTRY.register("flashing_light_blue_1s_z", FlashingLightBlue1sZBlock::new);
		FLASHING_LIGHT_BLUE_2S_A = REGISTRY.register("flashing_light_blue_2s_a", FlashingLightBlue2sABlock::new);
		FLASHING_LIGHT_BLUE_2S_B = REGISTRY.register("flashing_light_blue_2s_b", FlashingLightBlue2sBBlock::new);
		FLICKERING_LIGHT_BLUE_3S_A = REGISTRY.register("flickering_light_blue_3s_a", FlickeringLightBlue3sABlock::new);
		FLICKERING_LIGHT_BLUE_3S_B = REGISTRY.register("flickering_light_blue_3s_b", FlickeringLightBlue3sBBlock::new);
		FLICKERING_LIGHT_BLUE_3S_C = REGISTRY.register("flickering_light_blue_3s_c", FlickeringLightBlue3sCBlock::new);
		FLICKERING_LIGHT_BLUE_5S_A = REGISTRY.register("flickering_light_blue_5s_a", FlickeringLightBlue5sABlock::new);
		PULSING_LIGHT_BLUE_2S_A = REGISTRY.register("pulsing_light_blue_2s_a", PulsingLightBlue2sABlock::new);
		FLASHING_LIGHT_GRAY_1S_X = REGISTRY.register("flashing_light_gray_1s_x", FlashingLightGray1sXBlock::new);
		FLASHING_LIGHT_GRAY_1S_Y = REGISTRY.register("flashing_light_gray_1s_y", FlashingLightGray1sYBlock::new);
		FLASHING_LIGHT_GRAY_1S_Z = REGISTRY.register("flashing_light_gray_1s_z", FlashingLightGray1sZBlock::new);
		FLASHING_LIGHT_GRAY_2S_A = REGISTRY.register("flashing_light_gray_2s_a", FlashingLightGray2sABlock::new);
		FLASHING_LIGHT_GRAY_2S_B = REGISTRY.register("flashing_light_gray_2s_b", FlashingLightGray2sBBlock::new);
		FLICKERING_LIGHT_GRAY_3S_A = REGISTRY.register("flickering_light_gray_3s_a", FlickeringLightGray3sABlock::new);
		FLICKERING_LIGHT_GRAY_3S_B = REGISTRY.register("flickering_light_gray_3s_b", FlickeringLightGray3sBBlock::new);
		FLICKERING_LIGHT_GRAY_3S_C = REGISTRY.register("flickering_light_gray_3s_c", FlickeringLightGray3sCBlock::new);
		FLICKERING_LIGHT_GRAY_5S_A = REGISTRY.register("flickering_light_gray_5s_a", FlickeringLightGray5sABlock::new);
		PULSING_LIGHT_GRAY_2S_A = REGISTRY.register("pulsing_light_gray_2s_a", PulsingLightGray2sABlock::new);
		FLASHING_LIGHT_YELLOW_1S_X = REGISTRY.register("flashing_light_yellow_1s_x", FlashingLightYellow1sXBlock::new);
		FLASHING_LIGHT_YELLOW_1S_Y = REGISTRY.register("flashing_light_yellow_1s_y", FlashingLightYellow1sYBlock::new);
		FLASHING_LIGHT_YELLOW_1S_Z = REGISTRY.register("flashing_light_yellow_1s_z", FlashingLightYellow1sZBlock::new);
		FLASHING_LIGHT_YELLOW_2S_A = REGISTRY.register("flashing_light_yellow_2s_a", FlashingLightYellow2sABlock::new);
		FLASHING_LIGHT_YELLOW_2S_B = REGISTRY.register("flashing_light_yellow_2s_b", FlashingLightYellow2sBBlock::new);
		FLICKERING_LIGHT_YELLOW_3S_A = REGISTRY.register("flickering_light_yellow_3s_a", FlickeringLightYellow3sABlock::new);
		FLICKERING_LIGHT_YELLOW_3S_B = REGISTRY.register("flickering_light_yellow_3s_b", FlickeringLightYellow3sBBlock::new);
		FLICKERING_LIGHT_YELLOW_3S_C = REGISTRY.register("flickering_light_yellow_3s_c", FlickeringLightYellow3sCBlock::new);
		FLICKERING_LIGHT_YELLOW_5S_A = REGISTRY.register("flickering_light_yellow_5s_a", FlickeringLightYellow5sABlock::new);
		PULSING_LIGHT_YELLOW_2S_A = REGISTRY.register("pulsing_light_yellow_2s_a", PulsingLightYellow2sABlock::new);
		FLASHING_LIME_1S_X = REGISTRY.register("flashing_lime_1s_x", FlashingLime1sXBlock::new);
		FLASHING_LIME_1S_Y = REGISTRY.register("flashing_lime_1s_y", FlashingLime1sYBlock::new);
		FLASHING_LIME_1S_Z = REGISTRY.register("flashing_lime_1s_z", FlashingLime1sZBlock::new);
		FLASHING_LIME_2S_A = REGISTRY.register("flashing_lime_2s_a", FlashingLime2sABlock::new);
		FLASHING_LIME_2S_B = REGISTRY.register("flashing_lime_2s_b", FlashingLime2sBBlock::new);
		FLICKERING_LIME_3S_A = REGISTRY.register("flickering_lime_3s_a", FlickeringLime3sABlock::new);
		FLICKERING_LIME_3S_B = REGISTRY.register("flickering_lime_3s_b", FlickeringLime3sBBlock::new);
		FLICKERING_LIME_3S_C = REGISTRY.register("flickering_lime_3s_c", FlickeringLime3sCBlock::new);
		FLICKERING_LIME_5S_A = REGISTRY.register("flickering_lime_5s_a", FlickeringLime5sABlock::new);
		PULSING_LIME_2S_A = REGISTRY.register("pulsing_lime_2s_a", PulsingLime2sABlock::new);
		FLASHING_ORANGE_1S_X = REGISTRY.register("flashing_orange_1s_x", FlashingOrange1sXBlock::new);
		FLASHING_ORANGE_1S_Y = REGISTRY.register("flashing_orange_1s_y", FlashingOrange1sYBlock::new);
		FLASHING_ORANGE_1S_Z = REGISTRY.register("flashing_orange_1s_z", FlashingOrange1sZBlock::new);
		FLASHING_ORANGE_2S_A = REGISTRY.register("flashing_orange_2s_a", FlashingOrange2sABlock::new);
		FLASHING_ORANGE_2S_B = REGISTRY.register("flashing_orange_2s_b", FlashingOrange2sBBlock::new);
		FLICKERING_ORANGE_3S_A = REGISTRY.register("flickering_orange_3s_a", FlickeringOrange3sABlock::new);
		FLICKERING_ORANGE_3S_B = REGISTRY.register("flickering_orange_3s_b", FlickeringOrange3sBBlock::new);
		FLICKERING_ORANGE_3S_C = REGISTRY.register("flickering_orange_3s_c", FlickeringOrange3sCBlock::new);
		FLICKERING_ORANGE_5S_A = REGISTRY.register("flickering_orange_5s_a", FlickeringOrange5sABlock::new);
		PULSING_ORANGE_2S_A = REGISTRY.register("pulsing_orange_2s_a", PulsingOrange2sABlock::new);
		FLASHING_PINK_1S_X = REGISTRY.register("flashing_pink_1s_x", FlashingPink1sXBlock::new);
		FLASHING_PINK_1S_Y = REGISTRY.register("flashing_pink_1s_y", FlashingPink1sYBlock::new);
		FLASHING_PINK_1S_Z = REGISTRY.register("flashing_pink_1s_z", FlashingPink1sZBlock::new);
		FLASHING_PINK_2S_A = REGISTRY.register("flashing_pink_2s_a", FlashingPink2sABlock::new);
		FLASHING_PINK_2S_B = REGISTRY.register("flashing_pink_2s_b", FlashingPink2sBBlock::new);
		FLICKERING_PINK_3S_A = REGISTRY.register("flickering_pink_3s_a", FlickeringPink3sABlock::new);
		FLICKERING_PINK_3S_B = REGISTRY.register("flickering_pink_3s_b", FlickeringPink3sBBlock::new);
		FLICKERING_PINK_3S_C = REGISTRY.register("flickering_pink_3s_c", FlickeringPink3sCBlock::new);
		FLICKERING_PINK_5S_A = REGISTRY.register("flickering_pink_5s_a", FlickeringPink5sABlock::new);
		PULSING_PINK_2S_A = REGISTRY.register("pulsing_pink_2s_a", PulsingPink2sABlock::new);
		FLASHING_PURPLE_1S_X = REGISTRY.register("flashing_purple_1s_x", FlashingPurple1sXBlock::new);
		FLASHING_PURPLE_1S_Y = REGISTRY.register("flashing_purple_1s_y", FlashingPurple1sYBlock::new);
		FLASHING_PURPLE_1S_Z = REGISTRY.register("flashing_purple_1s_z", FlashingPurple1sZBlock::new);
		FLASHING_PURPLE_2S_A = REGISTRY.register("flashing_purple_2s_a", FlashingPurple2sABlock::new);
		FLASHING_PURPLE_2S_B = REGISTRY.register("flashing_purple_2s_b", FlashingPurple2sBBlock::new);
		FLICKERING_PURPLE_3S_A = REGISTRY.register("flickering_purple_3s_a", FlickeringPurple3sABlock::new);
		FLICKERING_PURPLE_3S_B = REGISTRY.register("flickering_purple_3s_b", FlickeringPurple3sBBlock::new);
		FLICKERING_PURPLE_3S_C = REGISTRY.register("flickering_purple_3s_c", FlickeringPurple3sCBlock::new);
		FLICKERING_PURPLE_5S_A = REGISTRY.register("flickering_purple_5s_a", FlickeringPurple5sABlock::new);
		PULSING_PURPLE_2S_A = REGISTRY.register("pulsing_purple_2s_a", PulsingPurple2sABlock::new);
		FLASHING_WHITE_1S_X = REGISTRY.register("flashing_white_1s_x", FlashingWhite1sXBlock::new);
		FLASHING_WHITE_1S_Y = REGISTRY.register("flashing_white_1s_y", FlashingWhite1sYBlock::new);
		FLASHING_WHITE_1S_Z = REGISTRY.register("flashing_white_1s_z", FlashingWhite1sZBlock::new);
		FLASHING_WHITE_2S_A = REGISTRY.register("flashing_white_2s_a", FlashingWhite2sABlock::new);
		FLASHING_WHITE_2S_B = REGISTRY.register("flashing_white_2s_b", FlashingWhite2sBBlock::new);
		FLICKERING_WHITE_3S_A = REGISTRY.register("flickering_white_3s_a", FlickeringWhite3sABlock::new);
		FLICKERING_WHITE_3S_B = REGISTRY.register("flickering_white_3s_b", FlickeringWhite3sBBlock::new);
		FLICKERING_WHITE_3S_C = REGISTRY.register("flickering_white_3s_c", FlickeringWhite3sCBlock::new);
		FLICKERING_WHITE_5S_A = REGISTRY.register("flickering_white_5s_a", FlickeringWhite5sABlock::new);
		PULSING_WHITE_2S_A = REGISTRY.register("pulsing_white_2s_a", PulsingWhite2sABlock::new);
		FLASHING_YELLOW_1S_X = REGISTRY.register("flashing_yellow_1s_x", FlashingYellow1sXBlock::new);
		FLASHING_YELLOW_1S_Y = REGISTRY.register("flashing_yellow_1s_y", FlashingYellow1sYBlock::new);
		FLASHING_YELLOW_1S_Z = REGISTRY.register("flashing_yellow_1s_z", FlashingYellow1sZBlock::new);
		FLASHING_YELLOW_2S_A = REGISTRY.register("flashing_yellow_2s_a", FlashingYellow2sABlock::new);
		FLASHING_YELLOW_2S_B = REGISTRY.register("flashing_yellow_2s_b", FlashingYellow2sBBlock::new);
		FLICKERING_YELLOW_3S_A = REGISTRY.register("flickering_yellow_3s_a", FlickeringYellow3sABlock::new);
		FLICKERING_YELLOW_3S_B = REGISTRY.register("flickering_yellow_3s_b", FlickeringYellow3sBBlock::new);
		FLICKERING_YELLOW_3S_C = REGISTRY.register("flickering_yellow_3s_c", FlickeringYellow3sCBlock::new);
		FLICKERING_YELLOW_5S_A = REGISTRY.register("flickering_yellow_5s_a", FlickeringYellow5sABlock::new);
		PULSING_YELLOW_2S_A = REGISTRY.register("pulsing_yellow_2s_a", PulsingYellow2sABlock::new);
		ARCADE_CABINET = REGISTRY.register("arcade_cabinet", ArcadeCabinetBlock::new);
		OPEN_SIGN_RED = REGISTRY.register("open_sign_red", OpenSignRedBlock::new);
		OPEN_SIGN_PINK = REGISTRY.register("open_sign_pink", OpenSignPinkBlock::new);
		NEON_CYBER_SIGN = REGISTRY.register("neon_cyber_sign", NeonCyberSignBlock::new);
		NEON_EDGE_CYAN_BLOCK = REGISTRY.register("neon_edge_cyan_block", NeonEdgeCyanBlockBlock::new);
		NEON_EDGE_MAGENTA_BLOCK = REGISTRY.register("neon_edge_magenta_block", NeonEdgeMagentaBlockBlock::new);
		NEON_DARK_MAGENTA_BLOCK = REGISTRY.register("neon_dark_magenta_block", NeonDarkMagentaBlockBlock::new);
		NEON_DARK_CYAN_BLOCK = REGISTRY.register("neon_dark_cyan_block", NeonDarkCyanBlockBlock::new);
		BIT_WISP = REGISTRY.register("bit_wisp", BitWispBlock::new);
		RETRO_GREEN_BLOCK = REGISTRY.register("retro_green_block", RetroGreenBlockBlock::new);
		RETRO_RED_BLOCK = REGISTRY.register("retro_red_block", RetroRedBlockBlock::new);
		RETRO_YELLOW_BLOCK = REGISTRY.register("retro_yellow_block", RetroYellowBlockBlock::new);
		RETRO_WHITE_BLOCK = REGISTRY.register("retro_white_block", RetroWhiteBlockBlock::new);
		RETRO_PASTEL_BLOCK = REGISTRY.register("retro_pastel_block", RetroPastelBlockBlock::new);
		NEON_EDGE_BLUE_BLOCK = REGISTRY.register("neon_edge_blue_block", NeonEdgeBlueBlockBlock::new);
		NEON_EDGE_BROWN_BLOCK = REGISTRY.register("neon_edge_brown_block", NeonEdgeBrownBlockBlock::new);
		NEON_EDGE_BUBBLEGUM_BLOCK = REGISTRY.register("neon_edge_bubblegum_block", NeonEdgeBubblegumBlockBlock::new);
		NEON_EDGE_GRAY_BLOCK = REGISTRY.register("neon_edge_gray_block", NeonEdgeGrayBlockBlock::new);
		NEON_EDGE_GREEN_BLOCK = REGISTRY.register("neon_edge_green_block", NeonEdgeGreenBlockBlock::new);
		NEON_EDGE_LIGHT_BLUE_BLOCK = REGISTRY.register("neon_edge_light_blue_block", NeonEdgeLightBlueBlockBlock::new);
		NEON_EDGE_LIGHT_GRAY_BLOCK = REGISTRY.register("neon_edge_light_gray_block", NeonEdgeLightGrayBlockBlock::new);
		NEON_EDGE_LIGHT_YELLOW_BLOCK = REGISTRY.register("neon_edge_light_yellow_block", NeonEdgeLightYellowBlockBlock::new);
		NEON_EDGE_LIME_BLOCK = REGISTRY.register("neon_edge_lime_block", NeonEdgeLimeBlockBlock::new);
		NEON_EDGE_ORANGE_BLOCK = REGISTRY.register("neon_edge_orange_block", NeonEdgeOrangeBlockBlock::new);
		NEON_EDGE_PINK_BLOCK = REGISTRY.register("neon_edge_pink_block", NeonEdgePinkBlockBlock::new);
		NEON_EDGE_PURPLE_BLOCK = REGISTRY.register("neon_edge_purple_block", NeonEdgePurpleBlockBlock::new);
		NEON_EDGE_RED_BLOCK = REGISTRY.register("neon_edge_red_block", NeonEdgeRedBlockBlock::new);
		NEON_EDGE_WHITE_BLOCK = REGISTRY.register("neon_edge_white_block", NeonEdgeWhiteBlockBlock::new);
		NEON_EDGE_YELLOW_BLOCK = REGISTRY.register("neon_edge_yellow_block", NeonEdgeYellowBlockBlock::new);
		NEON_EDGE_BLACK_BLOCK = REGISTRY.register("neon_edge_black_block", NeonEdgeBlackBlockBlock::new);
		NEON_DARK_BLUE_BLOCK = REGISTRY.register("neon_dark_blue_block", NeonDarkBlueBlockBlock::new);
		NEON_DARK_BROWN_BLOCK = REGISTRY.register("neon_dark_brown_block", NeonDarkBrownBlockBlock::new);
		NEON_DARK_BUBBLEGUM_BLOCK = REGISTRY.register("neon_dark_bubblegum_block", NeonDarkBubblegumBlockBlock::new);
		NEON_DARK_GRAY_BLOCK = REGISTRY.register("neon_dark_gray_block", NeonDarkGrayBlockBlock::new);
		NEON_DARK_GREEN_BLOCK = REGISTRY.register("neon_dark_green_block", NeonDarkGreenBlockBlock::new);
		NEON_DARK_LIGHT_BLUE_BLOCK = REGISTRY.register("neon_dark_light_blue_block", NeonDarkLightBlueBlockBlock::new);
		NEON_DARK_LIGHT_GRAY_BLOCK = REGISTRY.register("neon_dark_light_gray_block", NeonDarkLightGrayBlockBlock::new);
		NEON_DARK_LIGHT_YELLOW_BLOCK = REGISTRY.register("neon_dark_light_yellow_block", NeonDarkLightYellowBlockBlock::new);
		NEON_DARK_LIME_BLOCK = REGISTRY.register("neon_dark_lime_block", NeonDarkLimeBlockBlock::new);
		NEON_DARK_ORANGE_BLOCK = REGISTRY.register("neon_dark_orange_block", NeonDarkOrangeBlockBlock::new);
		NEON_DARK_PINK_BLOCK = REGISTRY.register("neon_dark_pink_block", NeonDarkPinkBlockBlock::new);
		NEON_DARK_PURPLE_BLOCK = REGISTRY.register("neon_dark_purple_block", NeonDarkPurpleBlockBlock::new);
		NEON_DARK_RED_BLOCK = REGISTRY.register("neon_dark_red_block", NeonDarkRedBlockBlock::new);
		NEON_DARK_WHITE_BLOCK = REGISTRY.register("neon_dark_white_block", NeonDarkWhiteBlockBlock::new);
		NEON_DARK_YELLOW_BLOCK = REGISTRY.register("neon_dark_yellow_block", NeonDarkYellowBlockBlock::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}